spring.application.name=dam-monitor-backend

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:dammonitordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=t

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (optional - for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Azure Storage Configuration
azure.storage.account-name=${AZURE_STORAGE_ACCOUNT_NAME:}
azure.storage.account-key=${AZURE_STORAGE_ACCOUNT_KEY:}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:dam-images}

# Earth Engine Config
google.earth.engine.service.account.key=classpath:civic-source-416013-b1d87381b895.json
google.earth.engine.project.id=civic-source-416013
